# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(220, 190, 341, 71))
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitButton.setObjectName("submitButton")
        self.upperBound = QtWidgets.QLineEdit(self.centralwidget)
        self.upperBound.setGeometry(QtCore.QRect(400, 120, 181, 51))
        self.upperBound.setAlignment(QtCore.Qt.AlignCenter)
        self.upperBound.setObjectName("upperBound")
        self.lowerBound = QtWidgets.QLineEdit(self.centralwidget)
        self.lowerBound.setGeometry(QtCore.QRect(200, 120, 181, 51))
        self.lowerBound.setAlignment(QtCore.Qt.AlignCenter)
        self.lowerBound.setObjectName("lowerBound")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 50, 381, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.outputField = QtWidgets.QLabel(self.centralwidget)
        self.outputField.setGeometry(QtCore.QRect(280, 280, 241, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.outputField.setFont(font)
        self.outputField.setFrameShape(QtWidgets.QFrame.Panel)
        self.outputField.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputField.setText("")
        self.outputField.setTextFormat(QtCore.Qt.RichText)
        self.outputField.setAlignment(QtCore.Qt.AlignCenter)
        self.outputField.setObjectName("outputField")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RandomNumberUI"))
        self.submitButton.setText(_translate("MainWindow", "Generate Random Number"))
        self.upperBound.setPlaceholderText(_translate("MainWindow", "Upper Bound"))
        self.lowerBound.setPlaceholderText(_translate("MainWindow", "Lower Bound"))
        self.label.setText(_translate("MainWindow", "Enter Lower and Upper  bounds"))
